### ISSUE TITLE
Policy with YAML anchors doesn't load correctly

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-api-python3#62] opened 2020-09-11 15:08 UTC
## Summary
When attempting to load a policy that includes YAML anchors, it doesn't load successfully and doesn't error.

From @whip113:
> It appears that the policy load method might not be working as expected. I've used it in the past successfully, but not with a YAML anchor. That's what we were doing this time, and while the python client didn't show any errors loading the policy, it also didn't create the host. I switched to the CLI and as the same user, loading the same policy, into the same branch as I tried with python the host was created.

## Steps to Reproduce
Attempt to load a policy with the Python client like:
```
- &my-hosts
  - !host cxflow_host
- !grant
  role: !group consumers
  member: *my-hosts
```

## Expected Results
The host will be created and will be a member of the `consumers` group.

## Actual Results (including error logs, if applicable)
The host is not created, and no errors are given.

## Reproducible
   * [ ] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
Unknown

## Environment setup
Unknown

**Comment by sgnn7** [comment] 2020-09-11 17:04
Unable to reproduce

- `test_policy.yml`
```yaml
- !group consumers

- &my-hosts
  - !host my_host

- !grant
  role: !group consumers
  member: *my-hosts
```

- `./pkg_bin/conjur-cli ... policy apply root test_policy.yml`
```sh-session
...
{
    "created_roles": {
        "dev:host:my_host": {
            "id": "dev:host:my_host",
            "api_key": "sv58d62yz20bh114f7ntz3cv02dy4afd2bqx3nz2rzb44x3qy385k"
        }
    },
    "version": 16
}
```

Once the host is created, neither conjur CLI nor python API will be able to get the key again though. They both return the following data since no role is created:
```
{
    "created_roles": {},
    "version": 17
}
```

**Comment by sgnn7** [comment] 2020-09-11 17:45
Confirmed w/ @whip113 as not reproducible at this point. Closing.

**Closed by sgnn7** 2020-09-11 17:45 UTC
Labels: component/conjur-sdk, kind/bug, triage/needs-info, triage/not-reproducible
