### ISSUE TITLE
Input Validations

### ISSUE THREAD

**Issue by tzheleznyak** [cyberark/conjur-api-python3#175] opened 2021-02-07 10:41 UTC
- [ ] Map client inputs over the code and what are the  legitimate inputs there
- [ ] Add input validation in these places

**Comment by sigalsax** [comment] 2021-07-05 08:11
closing as this is a duplicate of https://github.com/cyberark/conjur-api-python3/issues/157

**Closed by sigalsax** 2021-07-05 08:11 UTC
Labels: component/conjur-sdk, kind/enhancement
